sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile.dev .

script:
  - docker run docker-react npm run test -- --coverage

deploy:
  provider: "elasticbeanstalk"
  region: "eu-west-1"
  app: "docker-react-cloud"   
  env: "DockerReactCloud-env"   
  bucket_name: "elasticbeanstalk-eu-west-1-229569770452"
  bucket_path: "docker-react-cloud"
  on:
    branch: "master"
  access_key_id: "AKIATK43MWPKPJSSQKW5"    
  secret_access_key:
    secure: "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"   
